### ISSUE TITLE
Add multi-version Doxygen publishing to Github Pages

### ISSUE THREAD

**Issue by saxbophone** [saxbophone/CPP20-Cross-Platform-Template#7]
I recently rolled a basic but functional feature for a personal project which uses Github Actions to automatically build and publish Doxygen documentation to the github-pages branch, in a way which allows for multiple versions of the documentation to live together in the directory (with a tiny HTML fragment in the index to auto-redirect to the latest docs).

It'd be great to include this in the template.

**Comment by mirestrepo** [comment]
Hi @saxbophone I'm looking for multi-version gh action for a project. Would you mind sharing your solution?. Thanks in advance!

**Comment by saxbophone** [comment]
Hi @mirestrepo thank you for your question. I will be happy to share my solution. Please stay tuned and I will update this project soon to include the versioned docs implementation.

**Comment by saxbophone** [comment]
The implementation for the multi-versioned docs is provided in the linked commit and has been merged into the master branch. I am shortly going to amend the docs and add some usability improvements before making a new release.

**Comment by saxbophone** [comment]
v0.4.0 has now been released, see latest README for usage instructions. I hope it's useful to you, thanks for reminding me about it.

**Comment by mirestrepo** [comment]
@saxbophone Thank you so much! We'll give it a try!
